services:
    eliza:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data:/app/data
        env_file:
            - .env
        ports:
            - "3000:3000"
