name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hedgehive/agent:latest
            ghcr.io/hedgehive/agent:${{ github.sha }}
          labels: |
            org.opencontainers.image.created=${{ github.event.push.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=https://github.com/hedgehive/agent
            org.opencontainers.image.title=${{ github.event.repository.name }}

      - name: Image digest
        run: |
          echo "Docker image digest: ${{ steps.docker-build.outputs.digest }}"
